### ISSUE TITLE
CRAN submission?

### ISSUE THREAD

**Issue by wlandau** [richfitz/remake#101]
I'm curious about your plans for a CRAN submission. You mentioned the possibility in [#24](https://github.com/richfitz/remake/issues/24).

**Comment by wlandau** [comment]
Just as information, I suppose I should say that my own packages [remakeGenerator](https://github.com/wlandau/remakeGenerator) and [parallelRemake](https://github.com/wlandau/parallelRemake) are CRAN-ready except for their dependence on `remake`.

**Comment by richfitz** [comment]
Ah, I see. Would be nice to get it up by the end of the year, I suppose.  The only issue is getting enough time to polish it off.  The test suite is likely to cause havok on CRAN as there's lots of tests that are a bit funky (installing packages, downloading files, etc), so those will need to be reviewed.

**Comment by wlandau** [comment]
Thanks @richfitz, I'm a huge fan of `remake`. Let me know if there's anything I can do.

**Comment by bpbond** [comment]
Agreed - `remake` not being on CRAN is a bit of a block for our use case too. If I can help push it in this direction, let me know.

**Comment by richfitz** [comment]
Sorry - I would like to get it on CRAN but there's a fair bit of polish needed. I was hoping to get it up this year but it's not massively likely at this point.  I'm finishing up a big round of work on storr now, so hopefully I can get back to this

**Comment by bpbond** [comment]
Understood and no worries. I'm probably going to proceed with our project not using remake right now, but make sure things are architected with an eye towards doing so in the future. And again, when you have time to start thinking about CRAN submission, feel free to ping me if useful.

**Comment by cderv** [comment]
Hi,  is there some news about going to CRAN or is this abandoned prefering other alternatives ?
Just curious on where you are on this. Thanks!

**Comment by bpbond** [comment]
@cderv see @wlandau 's drake package: https://github.com/ropensci/drake

**Comment by cderv** [comment]
Thanks @bpbond I know about drake. I wonder if this replace remake. I find sometime remake to be simpler than drake when the richest features from drake are not needed.

**Comment by wlandau** [comment]
I have also heard some users prefer remake because it is more lightweight. Downsizing is a much higher priority for drake now than in the last couple years. My major development goals for 2019 are to reduce dependencies on external packages, improve speed, and remove features that are no longer necessary (especially when it comes to HPC). The current development version already has major improvements in these first two areas.

**Comment by richfitz** [comment]
Hi folks - as is probably moderately apparent from the lack of commit activity in remake, it is parked. I still think that there are some good ideas in there, but am not sure how many have not yet been implemented by @wlandau into `drake` already

I moved jobs when development on this project stalled and the shift in focus has made remake (or similar) less personally useful to me.  Most of the stuff I write is just itch scratching.  But especially when Will is actively developing a project that tries to solve most of the same problems it seems silly to try and get in the way when I've got other stuff I need more urgently.

**Comment by jordansread** [comment]
well great job on `remake` @richfitz 
It has been a lot of fun to use and discuss patterns within our group over the years.

**Comment by cderv** [comment]
Thank you very much for this answer. Thank you @richfitz for you work ! 
I will then concentrate on drake with @wlandau ongoing work !

**Comment by wlandau** [comment]
@richfitz, I second @jread-usgs and @cderv. `remake` met such an important need, and you made brilliant design choices. My favorites:

1. Static code analysis to automatically resolve dependencies.
1. Sophisticated caching of arbitrary R objects as targets.
1. Reliance on hashes, especially since the caching already requires serialization.

Seeing these features in a successful implementation really helped me begin to think about `drake`. In fact, without the solutions you developed for `remake`, `drake` would probably not exist. It is a privilege to continue the work you started.
