### ISSUE TITLE
License and copyright

### ISSUE THREAD

**Issue by wlandau** [richfitz/remake#139]
`R CMD check --as-cran` told me this:

```
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Rich FitzJohn <rich.fitzjohn@gmail.com>’

New submission

License components with restrictions and base license permitting such:
  BSD_2_clause + file LICENSE
File 'LICENSE':
  YEAR: 2014
  COPYRIGHT HOLDER: Richard G. FitzJohn
```

I'm not actually sure if R is complaining about the license or just stating an observation. Also, you may wish to update the copyright year to 2016 or 2014-2016.

**Comment by richfitz** [comment]
This is just information for the CRAN gate keepers. The first time I saw it I thought it was a problem too. I'll push a change updating the licence year soon which will close this.
