### ISSUE TITLE
Two questions re using remake with R package code

### ISSUE THREAD

**Issue by bpbond** [richfitz/remake#142]
I have a data-build system **X**, composed of a _lot_ of R files, some of which depend on data from each other, quite complex in their interactions, that culminates in several hundred XML output files. **X** is currently written as an R package because of the ancillary benefits this brings: automated and versioned dependency handling, test code, Roxgyen documentation, vignettes, etc. 

Question 1: is there any reason not do this--use `remake` inside a package structure? It seems like that would let me have both the testing, documentation, and distribution advantages that come with an R package, but also remake's power. I've written a small prototype package that builds one of X's products using remake. All seems OK, but am I missing a reason not to do this?

Question 2: how stable (in terms of API) is `remake`? Do you have a timeline for CRAN submission?

Thanks for your work on this @richfitz

**Comment by wlandau** [comment]
@bpbond I've used remake inside a package structure too, and I also like it. See #123 for the discussion on further integration. If you try to install your custom package and run it that way, though, remake no longer tracks your functions (#85). This seems like it has to do with how `walk()` is implemented in [code_dependencies.R](https://github.com/richfitz/remake/blob/master/R/code_dependencies.R). As for CRAN, there's the [CRAN release milestone](https://github.com/richfitz/remake/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CRAN+release%22) and #101.

**Comment by bpbond** [comment]
Thanks @wlandau - that's really useful. So it seems like remake and package structures play reasonably nice with each other during development, but less so after installation. OK.

**Comment by richfitz** [comment]
1. I'm interested in seeing more what people are doing in packages.  As @wlandau says it's not well supported in the current implementation, but there's no reason why it can't be made to work better.  The only real issue IMO is allowing analysing the package functions to depend on changes to the code, and that should not be that terrible to do.

2. The package is largely API stable (especially as I've not been able to commit much time at all this year to it).  Once it hits CRAN (#101) I'd like to be able to stand by the API properly as I can't abide packages breaking things.  The core yaml format has stayed the same for a long time and I'm happy with it (though not everyone is #2, #20).

**Comment by bpbond** [comment]
Thanks. See my comment in #101. Basically, I'm hoping to get the benefits of packaging during development, while allowing our end users to benefit from remake's smarts when they build the data system.
