### ISSUE TITLE
Bindings created by create_bindings() should never make

### ISSUE THREAD

**Issue by krlmlr** [richfitz/remake#144]
only fetch. Calling make() in an active binding can be very disruptive, especially in an IDE that starts querying these bindings when I edit source files that alter the value of a binding. Creating bindings will then be a faster version of dump_environment(), we might get rid of the latter then (unless there's a use case I haven't considered).

**Comment by richfitz** [comment]
Ouch, sounds bad.

I like `dump_environment()` because it's easier to wrap my head around and provides an escape-hatch of sorts.

**Comment by krlmlr** [comment]
I don't understand the check for `obj$config$active` in active_bindings.R, though. Can we just ignore that value and simply fetch?

**Comment by richfitz** [comment]
There may have been a disable/enable switch at some point, probably related to the interactive remake experimentation.  It can just be removed
