### ISSUE TITLE
Stale handles problem

### ISSUE THREAD

**Issue by sakrejda** [richfitz/remake#148]
Sometimes handles (for example database connections) will look up-to-date from remake's perpsective but in fact be stale because the outside resource is disconnected.  There's probably a nice way to handle this in remake but it's not clear from the doc how to do this.  Maybe allow a function to be defined in the `.yml` file that checks if the object is up to date or not.

**Comment by sakrejda** [comment]
Database handles go stale mid-build anyway and I'm pretty sure that's going to be a general problem with handles, I guess it just needs a solution outside of a build system.

**Comment by richfitz** [comment]
Yeah, not really sure what the best bet here would be (especially as I've not seen it personally).  Probably, as you say, something around the handle to keep it fresh in the user-code.  Sorry!
