### ISSUE TITLE
targets not rebuilt with create_bindings() when source edited

### ISSUE THREAD

**Issue by fmichonneau** [richfitz/remake#154]
With the current version (902ec7a) on GitHub , if using `create_bindings()`, I noticed that if a function on which a target depends on is edited, the function is not re-evaluated automatically. In the past, it used to be the case.

**Comment by krlmlr** [comment]
Yes, this is #145. The previous approach is very brittle, because some IDEs access the active bindings during tasks like autocompletion. Please call `make()` to recreate, you should be able to access the updated values after that.
