### ISSUE TITLE
Warn when some packages not installed?

### ISSUE THREAD

**Issue by RemkoDuursma** [richfitz/remake#16]
Since `maker.yml` can include the list of packages required, and `m$install_packages()` installs the missing ones, would it be useful to have a warning like,

```
> m <- maker()
Warning: some required packages not installed. Run m$install_packages() or proceed at your own risk.
```

Or even as an argument:

```
m <- maker(install_packages=TRUE)
```

**Comment by richfitz** [comment]
I've just changed the default behaviour to load all packages on startup; that means that you'll get an *error* in this case.  I think that errors are the best way forward here, really, given that target-based `packages:` field are available.  But if an `ignore_library_errors` option is desirable?

**Comment by RemkoDuursma** [comment]
error sounds good, this would cause the error right at the start rather than sometime half-way during the execution of code (which was the problem I encountered). I can't think of a reason to have `ignore_library_errors` because it can then be expected the code to fail anyway, unless packages are listed in `packages:` that are not needed anyway (maybe I am missing something).

**Comment by richfitz** [comment]
OK, new logic is done:

* By default maker tries to load all packages on startup.  This can be a bit slow sometimes, unfortunately.  It does not load packages that are loaded for specific targets only, but perhaps it should warn about them.
* Setting the global option `options(maker.install.missing.packages=TRUE)` will set the error action after failing to load all packages to try and then continue.  This is *really* hard to test but does seem to work.

I'll try and get the package-specific warnings done and then close this.

**Comment by richfitz** [comment]
So, in the end you do get a warning on load - I disabled loading packages until the last minute because some packages are slow to load.
