### ISSUE TITLE
Is there a way to get remake to detect changes in input files?

### ISSUE THREAD

**Issue by kendonB** [richfitz/remake#164]
I have a case where I'd like remake to store the fingerprints of a bunch of existing input files and rerun the dependent analyses if one of them changes. Is this possible?

The [documentation](https://github.com/richfitz/remake/blob/master/doc/concepts.md) says "implicit: these are file targets that are depended on somewhere in your process, but for which no rule exists. You can't build these of course. However, remake will build a target for them so we can monitor changes." However, I can't find an example of an already downloaded file being used in remake.

**Comment by wlandau** [comment]
Remake already does this, I believe. Try this `remake.yml` with your own file `data.txt`.

```r
targets:
  all:
    depends:
    - data
  data:
    command:
      readLines("data.txt")
```

**Comment by kendonB** [comment]
``depends`` was it. Thanks!
