### ISSUE TITLE
Did you mean?

### ISSUE THREAD

**Issue by dfalster** [richfitz/remake#19]
It's quite common to make spelling mistakes when writing maker files. The current error messages are OK, but could usefully suggest spelling as one of possible problems.

Better yet, you could add a "Did you mean" function, which compares the incorrect name against actual names and makes suggestions. 

@RemkoDuursma mentioned a recent R package that might be helpful here,  perhaps [Rdym](http://www.r-bloggers.com/a-did-you-mean-feature-for-r/)?

**Comment by RemkoDuursma** [comment]
Yes it is Rdym, I tried it and worked quite well.

--: Sent from my phone :--

**Comment by richfitz** [comment]
Hmm. Looks like that package is not available on CRAN and mostly exists to intercept `stop` errors (done via `.onLoad()`.  Might be possible to take the same basic approach but just using `agrep` or something...

**Comment by dfalster** [comment]
"did you mean" functionality in remake is proving very useful - thanks for implementing!
