### ISSUE TITLE
New package name, as maker won't be allowed on CRAN

### ISSUE THREAD

**Issue by richfitz** [richfitz/remake#24]
The package needs a new name :cry:

```
* checking CRAN incoming feasibility ... ERROR
Maintainer: ‘"Rich FitzJohn" <rich.fitzjohn@gmail.com>’
New submission
Conflicting package names (submitted: maker, existing: makeR [CRAN archive])
Components with restrictions and base license permitting such:
  BSD_2_clause + file LICENSE
File 'LICENSE':
  YEAR: 2014
  COPYRIGHT HOLDER: Richard G. FitzJohn
```

[Here's](http://cran.r-project.org/src/contrib/Archive/makeR/) the conflicting package.

Other conflicts:

* http://www.yandell-lab.org/software/maker.html (via [Matt MacManes](https://twitter.com/PeroMHC/status/525726821514760192))
* https://github.com/ComputationalProteomicsUnit/maker ([via author](https://twitter.com/lgatt0/status/542764176004087808))
* [Moar](https://github.com/search?utf8=%E2%9C%93&q=maker&type=Repositories&ref=searchresults)

Of course, Hadley [pointed out](https://twitter.com/hadleywickham/status/531924101787439104) that this was likely to be a problem a while ago, but I'd not run `R CMD check` with `--as-cran`.  So, new name ideas.

This should only change the name of the actual package, main object/function/script and repo.  References to `make` will probably stay as-is.

Ideas @mwpennell, @dfalster, @aammd?  Something that a punny logo can be made from?

**Comment by richfitz** [comment]
Actually, this will probably change the name of configuration files too (`maker.yml` -> `<fancy_new_name>.yml`), plus the storage in `.maker/`.

**Comment by fmichonneau** [comment]
remake?

baker? (follows a recipe, only 1 letter difference)

**Comment by dfalster** [comment]
How disappointing!

Here's a few ideas, haven't checked yet to see if they are already in use:


`Remake` or `Rmake`

- definition: "make (something) again or differently"
- pros:
- name has some connection to make, which will mean something to some people

`Rake`

- definition:  draw together with a rake or similar implement, make
(ground) smooth with a rake
- pros:
- connects ideas of `make` and `R`
- cons:
- name already used in other software (not in R though, i think)

`Conductor`  or `conductR`

- definition: "a person who directs the performance of an orchestra"
- pros:
- name links to role, overseeing the whole
- easy logo
- cons:
- ambiguity, there are multiple types of conductor

**Comment by richfitz** [comment]
`[rake](https://github.com/ruby/rake)` is Ruby's build tool so that's definitely out.  I'd wondered about remake or rmake, too.  I also like `baker`.

`buildr` is another possibility, though it's possibly hard to google for and might be confusing with `R CMD build`, R's "win builder", etc.

`worker`, as in workflows?

**Comment by dfalster** [comment]
remake is my fav so far

**Comment by aammd** [comment]
I like "remake", since it implies 1) connection to make 2) that it is an "updated" version, a kind of "make 2.0"

**Comment by richfitz** [comment]
remake is probably my favourite so far, too.  But there are (of course) a few other projects that use the name already:

* https://github.com/silene/remake
* https://github.com/tonyrog/remake
* https://github.com/rocky/remake

rmake is probably out because of an R project: (https://github.com/jpsimonroy/rmake).

Annoyingly we're going to make a release of the first project using maker (dfalster/baad) in the next few days so I'll have to do the rename before then :-/

**Comment by dfalster** [comment]
and `remaker` is probably a bit cumbersome.

At least none of the other `remake` packages are in R. Any evidence they
are widely used?

**Comment by richfitz** [comment]
Another advantage of `remake`: it comes complete with a themesong: https://www.youtube.com/watch?v=CMBeqNfYEYY

**Comment by richfitz** [comment]
New package https://github.com/richfitz/maker that does nothing more than forward to remake with a warning.

**Comment by richfitz** [comment]
Last thing to consider is whether to treat `maker.yml` files as suitable for use as a default for `remake.yml`.  I actually think no (though the files can be passed in of course).

**Comment by dfalster** [comment]
Could the new minimalist maker package accept maker.yml as default? That
would ensure back compatibility without overload new remake with multiple
defaults.

**Comment by richfitz** [comment]
Yeah, it does: https://github.com/richfitz/maker/tree/master/tests/testthat
