### ISSUE TITLE
Problem when sourcing entire directories in export script

### ISSUE THREAD

**Issue by dfalster** [richfitz/remake#25]
if your'e maker file contains something like

```
sources:
  - R
```
and then you run

```
m <- maker::maker()
m$script()
```

the output contains 

```
source("R")
```

which doesn't work. Instead need something like

```
tmp <- lapply(list.files("R", full.names=TRUE), source)
```
or use a `source_dir` command

**Comment by richfitz** [comment]
Thanks, I noticed this a couple of days ago and looks like I forgot to make an issue. Super easy fix as you suggest.
