### ISSUE TITLE
list_targets to ignore all target files

### ISSUE THREAD

**Issue by fmichonneau** [richfitz/remake#43]
I'm trying to debug something with my knitr file and I need to run knit interactively.

To make sure all my targets are available, I'd like to do something like:

```
e <- make_environment(list_targets())
```

This however doesn't quite work because list_targets also returns the target files.

Would it make sense to add an argument to list_targets so it only returns R object targets?

I'm happy to submit a PR if you think it would be useful.

**Comment by richfitz** [comment]
See the `type` argument to list targets, in particular `list_targets(type="object")`

**Comment by fmichonneau** [comment]
Perfect, sorry for the noise...
