### ISSUE TITLE
Best way to call remake::make() from a PBS script?

### ISSUE THREAD

**Issue by wcornwell** [richfitz/remake#59]
any ideas?

**Comment by richfitz** [comment]
Ah, HPC systems.  Such a joy to use.

If you run 

```r
remake::install_remake(".")
```

on the head node it will put some scripts in the working directory. Then your pbs script can include:

```sh
./remake
```

as the command and everything should work.

**Comment by wcornwell** [comment]
does remake.yml then have to be in the same folder as the remake scripts?

**Comment by richfitz** [comment]
Afraid so.  But I can set you up a change directory on the command line tool if that's useful.  I'm avoiding thinking about some deeper issues with working directories as it's much harder than it seems at first glance.

**Comment by wcornwell** [comment]
I've got this to work, now I think

**Comment by wlandau-lilly** [comment]
@wcornwell I know this is an old issue, but if you want to split up `remake` targets over multiple PBS jobs, another option is [parallelRemake](https://github.com/wlandau/parallelRemake)/[remakeGenerator](https://github.com/wlandau/remakeGenerator) using the `Makefile` and `shell.sh` in [described here](http://will-landau.com/parallelRemake/articles/parallelRemake.html#high-performance-computing): that is, if the overhead is worth your while.

**Comment by wcornwell** [comment]
@wlandau-lilly cool thanks.  I'll check it out.
