### ISSUE TITLE
dump_environment() stopped working

### ISSUE THREAD

**Issue by aammd** [richfitz/remake#75]
`remake::dump_environment()` produces the following error:

```r
[  DUMP ] 
Error in rawToChar(as.raw(x)) : 
  embedded nul in string: 'nZ\034\x92\xcf\xdbjG\xab\0\0\x9a\xb1\0\0\xa2w\xe5\x89\xcb'
In addition: Warning message:
In rawToChar(as.raw(x)) :
  out-of-range values treated as 0 in coercion to raw
```
I've found the same on multiple projects. Updating `remake` and `storr` doesn't help.

Here's the output of `traceback()`

```r
12: rawToChar(as.raw(x))
11: FUN(X[[i]], ...)
10: vapply(X, FUN, character(1), ...)
9: vcapply(x, decode64, char62, char63, USE.NAMES = FALSE)
8: decode64(ret, TRUE)
7: self$driver$list_keys(namespace)
6: sort(self$driver$list_keys(namespace))
5: src$list(namespace)
4: storr_copy(dest, self, list, namespace)
3: obj$store$objects$export(envir)
2: remake_dump_environment(obj, envir)
1: remake::dump_environment()
```

**Comment by aammd** [comment]
Closing, because all this required was to delete `.remake/` and rerun. 
It appears that this problem was caused by the switch to R 3.2.3  (on 64-bit linux)
Could the problem have been caused by a change in the serialization of raw vectors? from the release notes:
> The remaining instances in which serialization to a raw vector
      was limited to 2GB have been unlimited on a 64-bit platform, and
      in most cases serialization to a vector of more than 1GB will be
      substantially faster.

**Comment by richfitz** [comment]
Hi Andrew - I'm tweaking storr at the moment in the hope to get it off to CRAN shortly and have changed the db format slightly twice in the week before Christmas.  I had a hunch it would affect existing remake set ups and it appears to.  Once storr is on CRAN I will try very hard to prevent this happening again.
