### ISSUE TITLE
support specifying a function in depends?

### ISSUE THREAD

**Issue by jread-usgs** [richfitz/remake#81]
I find myself running into situations where it would be helpful to do

```
temperature.clean:
    command: munge_variable(temperature)
    depends:
      - munge_temperature
```
where `munge_variable()` is a more general function that calls `munge_temperature()` for some things that are specific to `temperature`. 

I can handle this in a couple of ways:

1. break out munge_temperature() into a separate file, and depend on that file
```
temperature.clean:
    command: munge_variable(temperature)
    depends:
      - scripts/munge_temperature.R
```
2. have redundancy in the different functions for each `variable` (e.g., be OK with repeated code in `munge_temperature`, `munge_oxygen`, etc and call them directly as 
```
temperature.clean: 
    command: munge_temperature(temperature)`
```
3. Some other way? Not sure if there is a simpler pattern I can follow here, and apologies if there is.

Anyhow, the basic question here is whether you would support depending on something that is akin to `command`

**Comment by rBatt** [comment]
What file is `munge_temperature` in? A "munge.R" file containing several functions? I'm just trying to figure out if I have a similar case in my own workflow // if I understand.

I'm still pretty new to remake, and don't understand it that well. That said, almost all of the functionality is based on file differences, whereas you're talking about looking for a diff in an object, right? Obviously, that means writing the object to a file in the interim (probably part of what all those data files in .remake are about), which could be done pretty easily from within R.

**Comment by richfitz** [comment]
Hi!

I am meaning to get to this.  Short version is: if there is a workflow that can't easily be done and if it can be easily added to remake then I am more than happy to incorporate it into the package.  However, I'm not heavily working on remake at the moment as it's not central to my own work right now.

Just to clarify things though: remake does not use file differences for detecting changes in functions, it uses the parsed contents of the function instead.  It also detects functions *used* by other functions so for for the case above I would have thought it would work.

However, what might be going on is that if `munge_temperature` changes then all the other things that go through `munge_variable` will also be flagged for change.  I'm not sure.  Could you be a little more explicit about what the missing feature is, or preferably give a minimal example (if you do that then I can incorporate it as a test case - it can be very contrived of course).

I'll be travelling the next 2 weeks, so progress/communcation may be slow.

**Comment by jread-usgs** [comment]
Thanks @richfitz and @rBatt . I will put together a small working example to illustrate this and post it to this issue within the next two weeks. Thanks for your willingness to consider this.

**Comment by jread-usgs** [comment]
@richfitz in the process of creating a small working example, I verified that I am seeing the expected behavior and that I did something dumb in my larger, more complex use case. 

For posterity:

```yaml
sources:
  - example_script.R

targets:
  all:
    depends: data.out
      
  data.out:
    command: generic_fun()
```
###example_script.R:
```r
specific_fun <- function(data.in){
  data.in$dist
}

generic_fun <- function(){
  data.in <- head(cars)
  data.in$speed <- rev(data.in$speed)
  specific_fun(data.in)
}
```
###remake:
```r
remake::make()
[  READ ]          |  # loading sources
<  MAKE > all
[ BUILD ] data.out |  data.out <- generic_fun()
[ ----- ] all
```

trivial, but important change to `specific_fun` *does* trigger a re-build of data.out, as should happen:
```r
specific_fun <- function(data.in){
  rev(data.in$dist)
}

generic_fun <- function(){
  data.in <- head(cars)
  data.in$speed <- rev(data.in$speed)
  specific_fun(data.in)
}

remake::make()
[  READ ]          |  # loading sources
<  MAKE > all
[ BUILD ] data.out |  data.out <- generic_fun()
[ ----- ] all
```

so...smart package. User error.
