### ISSUE TITLE
Better rendering of dependency plots ("$diagram()")

### ISSUE THREAD

**Issue by richfitz** [richfitz/remake#9]
The current code is just a stub, really and won't work for real networks.  For example here is an issue from a nontrivial project ([dfalster/tree-p](https://github.com/dfalster/tree-p) -- currently private)
![tree-p](https://cloud.githubusercontent.com/assets/1558093/4672908/a4f73852-5598-11e4-9ee6-84e3d04b5693.png)

and here's another from [richfitz/modeladequacy](https://github.com/richfitz/modeladequacy):
![model-adequacy](https://cloud.githubusercontent.com/assets/1558093/4672923/df80e6d0-5598-11e4-8990-bbb1526cb839.png)

I think the idea is sound, but dealing with networks that are a reasonable size in a moderately automatic way is going to be hard!  Especially as the target names for filenames can be quite long.

**Comment by richfitz** [comment]
[DiagrammeR](https://github.com/rich-iannone/DiagrammeR) looks promising, and generating a force directed d3 graph (suggested by Karl Broman) is another option that sidesteps layout.

**Comment by dfalster** [comment]
Shift from igraph to DiagrammeR in cd6036572ab25f36b3a44a9260f5d657d03b84d9

**Comment by richfitz** [comment]
Yeah, good call.
