### ISSUE TITLE
Folder targets -- in place of file targets?

### ISSUE THREAD

**Issue by aammd** [richfitz/remake#93]
I have a workflow which begins with calling `dir()` on a directory of files. So I tried allowing the directory to be the place of an implicit "file" target in `remake.yml`:

``` yml
  filelist:
    command: dir("filefolder/")
```

This works fine once, but subseqent md5 checks complain:

```
Warning message:
In structure(.Call(Rmd5, files), names = files) :
  md5 failed on file 'filefolder/'
```

Is this a use case you'd like to include? Or should I just wrap `filefolder/` in `I()`? That latter approach sounds like a simple fix; maybe it should be suggested by a message?

**Comment by richfitz** [comment]
In your case, `I()` should be used, but I'm not sure if this is easy to reliably detect.  I'm planning on working on remake over the next few weeks (!) so will try and test this.

**Comment by krlmlr** [comment]
Is this related to #10?

**Comment by richfitz** [comment]
yup
