### ISSUE TITLE
Code dependencies fails for length 0 vectors

### ISSUE THREAD

**Issue by aammd** [richfitz/remake#97]
[this line](https://github.com/richfitz/remake/blob/refactor/R/code_dependencies.R#L21) is where a 0 - length object will end up, which causes the error 

`Error in exists(e_name, env) : invalid first argument`

**Comment by richfitz** [comment]
what do you mean zero length vectors? A zero length vector in the environment being scanned?

**Comment by aammd** [comment]
I don't understand! I just tried to write a test case for this, and it seems to work now. I find I can't reproduce the original error at all! Let's just forget this one happened.

**Comment by richfitz** [comment]
A [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug)! :bug:
